apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: default
spec:
  destination:
    namespace: redis
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: redis
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 17.8.3
    helm:
      valueFiles:
      - $values/redis.values.yaml
  - repoURL: 'https://github.com/fabricev/argocd-multi-sources.git'
    targetRevision: HEAD
    path: ./
    ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
