defaultRules:
  create: true
alertmanager:
  create: true
  ingress:
    enabled: true
    hosts:
      - "argocd.fabrice.local"
    tls:
      - hosts:
          - alertmanager.fabrice.local
        secretName: quickstart-example-tls-alertmanager
    paths:
      - /
grafana:
  enabled: false
