{
 "title": "Nodes Copy",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_node_info,node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU $node",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "targets": [
    {
     "expr": "  label_replace(sum(rate(node_cpu_seconds_total[$__rate_interval])) by (mode,instance), \"instance\", \"$1\", \"instance\", \"(.*):(.*)\")\n  * on (instance)\n  group_left(node)\n  label_replace(kube_node_info{node=\"$node\"}, \"instance\", \"$1\", \"internal_ip\", \"(.*)\")",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory: $node  ",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(node_memory_MemAvailable_bytes, \"instance\", \"$1\", \"instance\", \"(.*):(.*)\")\n  * on (instance)\ngroup_left(node)\n  label_replace(kube_node_info{node=\"$node\"}, \"instance\", \"$1\", \"internal_ip\", \"(.*)\")",
     "legendFormat": "Free"
    },
    {
     "expr": "label_replace(node_memory_MemTotal_bytes-node_memory_MemAvailable_bytes, \"instance\", \"$1\", \"instance\", \"(.*):(.*)\")\n  * on (instance)\ngroup_left(node)\n  label_replace(kube_node_info{node=\"$node\"}, \"instance\", \"$1\", \"internal_ip\", \"(.*)\")",
     "legendFormat": "Used"
    }
   ]
  }
 ]
}
{
 "title": "Default Dashboard",
 "description": "Test",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Namespace CPU usage",
   "type": "bargauge",
   "description": "Test desc",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(container_cpu_usage_seconds_total{container!=\"\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Namespace Memory usage",
   "type": "bargauge",
   "description": "Test desc",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(namespace) (container_memory_usage_bytes{container!=\"\"})",
     "legendFormat": "__auto"
    },
    { "expr": "contaoi", "legendFormat": "__auto" }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 6, "w": 13, "x": 11, "y": 0 } },
  { "title": "History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Namespace CPU usage",
   "type": "timeseries",
   "description": "Test desc",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(namespace) (rate(container_cpu_usage_seconds_total{container!=\"\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{container!=\"\"}[$__rate_interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Namespace Memory usage",
   "type": "timeseries",
   "description": "Test desc",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(namespace) (container_memory_usage_bytes{container!=\"\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (container_memory_usage_bytes{container!=\"\"})",
     "legendFormat": "total"
    }
   ]
  }
 ]
}