apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-default-datasource
  labels:
    grafana_datasource: "true"
data:
  datasource-prometheus.yaml: |-
    apiVersion: 1
    datasources:
      - name: New Prometheus 
        type: prometheus
        url: http://prometheus-operated.prometheus.svc:9090
