apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: kube-prometheus-stack
      repoURL: "https://prometheus-community.github.io/helm-charts"
      targetRevision: 70.7.0
      helm:
        skipCrds: true
        valueFiles:
          - $values/prometheus.values.yaml
    - repoURL: "https://github.com/fabricev/argocd-multi-sources.git"
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      {}
    syncOptions:
      - CreateNamespace=true
