apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: grafana
      repoURL: "https://grafana.github.io/helm-charts"
      targetRevision: 8.14.0
      helm:
        valueFiles:
          - $values/grafana.values.yaml
    - repoURL: "https://github.com/fabricev/argocd-multi-sources.git"
      targetRevision: HEAD
      ref: values
    - repoURL: "https://github.com/fabricev/argocd-multi-sources.git"
      targetRevision: HEAD
      path: grafana/
  syncPolicy:
    automated:
      {}
    syncOptions:
      - CreateNamespace=true
