apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.grafana: deployed
    notifications.argoproj.io/subscribe.on-sync-running.grafana: running
    notifications.argoproj.io/subscribe.on-sync-succeeded.grafana: synched
spec:
  destination:
    namespace: redis
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: redis
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 17.9.0
    helm:
      valueFiles:
      - $values/redis.values.yaml
  - repoURL: 'https://github.com/fabricev/argocd-multi-sources.git'
    targetRevision: HEAD
    ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
